// Generated by scripts/gen-abis.mjs from the Foundry artifact for FlipperLens. Do not edit by hand.
// Regenerate with `pnpm --filter @flipperdotfamily/sdk gen:abis`.

export const flipperLensAbi = [
  {
    "type": "function",
    "name": "claimables",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenList",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "outputs": [
      {
        "name": "amounts",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "flipsById",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FlipperLens.FlipView[]",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "player",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "createdAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "winChanceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "roll",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum FlipperHouseBase.Status"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "liability",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sellQuote",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "buyQuote",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "requestId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payoutBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "house",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct FlipperLens.HouseView",
        "components": [
          {
            "name": "flipper",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "treasury",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reserved",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLiability",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "rewardsAccrued",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "randomnessFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "listedTokens",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nextFlipId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "params",
            "type": "tuple",
            "internalType": "struct FlipperHouseBase.Params",
            "components": [
              {
                "name": "baseWinChanceBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "minWinChanceBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "flipperPayoutBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "minHouseEdgeBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxRouteCostBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "lossSlippageBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxBetBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "rewardsShareBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "listingMaxRouteCostBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "listingProbeBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "callbackGasLimit",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "swapGasLimit",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "guardianCancelDelay",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "playerCancelDelay",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "minListingProbe",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "flipperCallbackGasLimit",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "pendingTimeout",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "maxReservedBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "kellyBps",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxStake",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hi",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "baseOdds",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "pv",
        "type": "tuple",
        "internalType": "struct FlipperHouseBase.Preview",
        "components": [
          {
            "name": "code",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "sellQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buyQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "routeCostBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "winChanceBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liability",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLiability",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "randomnessFee",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pendingWins",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "player",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "fromId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "toId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FlipperLens.FlipView[]",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "player",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "createdAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "winChanceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "roll",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum FlipperHouseBase.Status"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "liability",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sellQuote",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "buyQuote",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "requestId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "payoutBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "previews",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amounts",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FlipperHouseBase.Preview[]",
        "components": [
          {
            "name": "code",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "sellQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buyQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "routeCostBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "winChanceBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liability",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxLiability",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "randomnessFee",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "surplus",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenView",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct FlipperLens.TokenView",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "blocked",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hops",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokens",
    "inputs": [
      {
        "name": "h",
        "type": "address",
        "internalType": "contract FlipperHouse"
      },
      {
        "name": "offset",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "limit",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FlipperLens.TokenView[]",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "blocked",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "adapter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hops",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "vault",
    "inputs": [
      {
        "name": "tv",
        "type": "address",
        "internalType": "contract TreasuryVault"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct FlipperLens.VaultView",
        "components": [
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "totalAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "freeAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "depositorShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "protocolShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePerShare",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "highWaterMark",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "protocolOwnedAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "depositorAssets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "performanceFeeBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "lockDuration",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "withdrawCooldown",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct FlipperLens.VaultPositionView",
        "components": [
          {
            "name": "shares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "assets",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unlockAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pendingShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "readyAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxWithdrawable",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "flipperBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "flipperAllowance",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
