#!/usr/bin/env node
// Reads the Foundry build artifacts in contracts/out and writes typed `as const` ABIs to src/abis/*.ts.
// The generated files are committed, so the SDK and the web app build without Foundry.
//
//   pnpm --filter @flipperdotfamily/sdk gen:abis            (after `forge build` in contracts/)
// contracts/ is github.com/flipperdotfamily/flipper-contracts, checked out beside this repo in flipper's monorepo;
// elsewhere, point FOUNDRY_OUT at its out/ directory.
//   FOUNDRY_OUT=/path/to/out pnpm ... gen:abis     (custom artifact dir)

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const outDir = resolve(process.env.FOUNDRY_OUT ?? join(pkgRoot, "../../contracts/out"));
const abisDir = join(pkgRoot, "src/abis");

/** [artifact contract name, exported const name, output file, optional (keep the hand-written file if missing)] */
const TARGETS = [
  ["FlipperHouse", "flipperHouseAbi", "flipperHouse"],
  ["FlipperLens", "flipperLensAbi", "flipperLens"],
  // $FLIPPER itself: holder rewards are built into the token (the epoch / Merkle HolderRewards contract is gone)
  ["FlipperRewardToken", "flipperRewardTokenAbi", "flipperRewardToken"],
  ["RevenueRouter", "revenueRouterAbi", "revenueRouter"],
  ["DutchAuctionConverter", "dutchAuctionConverterAbi", "dutchAuctionConverter"],
  ["HookitRouteAdapter", "hookitRouteAdapterAbi", "hookitRouteAdapter"],
  ["V4RouteAdapter", "v4RouteAdapterAbi", "v4RouteAdapter", true],
  ["V3RouteAdapter", "v3RouteAdapterAbi", "v3RouteAdapter", true],
  ["TreasuryVault", "treasuryVaultAbi", "treasuryVault"],
  // partners (ERC-8021 attribution): the registry the house resolves a flip's calldata suffix against
  ["PartnerRegistry", "partnerRegistryAbi", "partnerRegistry"],
  // the team's vault shares, locked for good (only the excess over the principal can be withdrawn)
  ["PrincipalLock", "principalLockAbi", "principalLock", true],
  // the immutable holder of the launch position NFT (fees → router; optionally UNCX-locked)
  ["LiquidityKeeper", "liquidityKeeperAbi", "liquidityKeeper", true],
  // "minimal ERC20": the OpenZeppelin IERC20Metadata interface (name/symbol/decimals + the IERC20 surface)
  ["IERC20Metadata", "erc20Abi", "erc20"],
];

if (!existsSync(outDir)) {
  console.error(`gen:abis: artifact directory not found: ${outDir}\nRun \`forge build\` in contracts/ first.`);
  process.exit(1);
}

/** Foundry writes out/<File>.sol/<Contract>.json, but nested source dirs can also produce nested folders.
 *  Collect every candidate and take the most recently written one. */
function findArtifact(name) {
  const hits = [];
  const walk = (dir, depth) => {
    if (depth > 4) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "build-info") continue;
        walk(p, depth + 1);
      } else if (entry.name === `${name}.json` && dir.endsWith(`${name}.sol`)) {
        hits.push(p);
      }
    }
  };
  walk(outDir, 0);
  if (hits.length === 0) return null;
  hits.sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
  return hits[0];
}

mkdirSync(abisDir, { recursive: true });
const index = [];
for (const [contract, constName, file, optional] of TARGETS) {
  const path = findArtifact(contract);
  if (!path) {
    if (!optional) throw new Error(`artifact for ${contract} not found under ${outDir}`);
    console.log(`gen:abis: ${contract.padEnd(20)} → not built yet; keeping the hand-written src/abis/${file}.ts`);
    index.push(`export { ${constName} } from "./${file}";`);
    continue;
  }
  const json = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(json.abi)) throw new Error(`${path} has no abi`);
  // (the header names the contract, not the artifact path: Foundry's compiler profiles emit duplicate artifacts
  // and the newest one wins, so a path here would churn between runs)
  const header =
    `// Generated by scripts/gen-abis.mjs from the Foundry artifact for ${contract}. Do not edit by hand.\n` +
    `// Regenerate with \`pnpm --filter @flipperdotfamily/sdk gen:abis\`.\n\n`;
  const body = `export const ${constName} = ${JSON.stringify(json.abi, null, 2)} as const;\n`;
  writeFileSync(join(abisDir, `${file}.ts`), header + body);
  index.push(`export { ${constName} } from "./${file}";`);
  console.log(`gen:abis: ${contract.padEnd(20)} → src/abis/${file}.ts (${json.abi.length} entries, from ${relative(outDir, path)})`);
}
// Hand-written ABIs that do not come from this repo's artifacts (third-party contracts).
index.push(`export { hookitLaunchFactoryAbi } from "./hookitLaunchFactory";`);
index.push(`export { poolManagerAbi } from "./poolManager";`);
index.push(`export { wethAbi } from "./weth";`);
// the pre-streaming name: holder rewards now live in the $FLIPPER token
index.push(`/** @deprecated holder rewards are built into $FLIPPER: use \`flipperRewardTokenAbi\` */\nexport { flipperRewardTokenAbi as holderRewardsAbi } from "./flipperRewardToken";`);
writeFileSync(join(abisDir, "index.ts"), `// Generated by scripts/gen-abis.mjs. Do not edit by hand.\n\n${index.join("\n")}\n`);
