#!/usr/bin/env node
// Writes src/abis/slim.ts: the protocol ABIs cut down to the functions and events this SDK's own code names (every
// error is kept, so reverts still decode). The client imports these; `@flipperdotfamily/sdk/abis` keeps exporting the full ABIs.
// Bundles that include the client (e.g. the widget's CDN build) shrink by ~40 KB. Runs after gen-abis.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");
const abis = join(src, "abis");
const SLIM = [
  ["flipperHouse", "flipperHouseAbi"],
  ["flipperLens", "flipperLensAbi"],
  ["flipperRewardToken", "flipperRewardTokenAbi"],
  ["revenueRouter", "revenueRouterAbi"],
  ["hookitRouteAdapter", "hookitRouteAdapterAbi"],
  ["v4RouteAdapter", "v4RouteAdapterAbi"],
  ["v3RouteAdapter", "v3RouteAdapterAbi"],
  ["treasuryVault", "treasuryVaultAbi"],
  ["partnerRegistry", "partnerRegistryAbi"],
  ["principalLock", "principalLockAbi"],
];
const PASS = [
  ["erc20", "erc20Abi"],
  ["weth", "wethAbi"],
  ["poolManager", "poolManagerAbi"],
  ["hookitLaunchFactory", "hookitLaunchFactoryAbi"],
];

// every string literal in the SDK's own sources (not the ABIs, not React)
const names = new Set();
for (const f of readdirSync(src)) {
  if (!f.endsWith(".ts")) continue;
  for (const m of readFileSync(join(src, f), "utf8").matchAll(/"([A-Za-z_][A-Za-z0-9_]*)"/g)) names.add(m[1]);
}

let out = "// Generated by scripts/slim-abis.mjs: the ABIs trimmed to what the SDK's client calls (all errors kept). Do not edit.\n\n";
for (const [file, name] of SLIM) {
  const text = readFileSync(join(abis, `${file}.ts`), "utf8");
  const json = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
  const abi = JSON.parse(json);
  const kept = abi.filter((x) => x.type === "error" || ((x.type === "function" || x.type === "event") && names.has(x.name)));
  out += `export const ${name} = ${JSON.stringify(kept)} as const;\n`;
  console.log(`slim-abis: ${name.padEnd(24)} ${abi.length} → ${kept.length} entries`);
}
for (const [file, name] of PASS) out += `export { ${name} } from "./${file}";\n`;
writeFileSync(join(abis, "slim.ts"), out);
