/**
 * The widget's string table. Override any key with the `strings` option; `{name}` placeholders are filled in at
 * render time. Built-in locales: en (default), es.
 */
export const en = {
  // header / wallet
  brand: "flipper",
  connect: "Connect wallet",
  connectShort: "Connect",
  connecting: "Connecting…",
  switchChain: "Switch to {chain}",
  switching: "Switching…",
  wrongNetwork: "Wrong network",
  tagline: "Double or nothing",
  taglineSub: "Heads pays {multiple} in {symbol}. Provably fair.",
  // CTA states
  loading: "Loading…",
  notLive: "Not live on this network yet",
  unreachable: "Can't reach {chain}",
  paused: "Flipping is paused",
  enterAmount: "Enter an amount",
  belowMin: "Minimum is {amount} {symbol}",
  aboveMax: "Maximum is {amount} {symbol}",
  insufficient: "Not enough {symbol}",
  needFee: "Need {native} for the randomness fee",
  pricing: "Pricing…",
  cantPrice: "Couldn't price this flip",
  flip: "Flip {amount} {symbol}",
  flipAgain: "Flip again",
  selectToken: "Select a token",
  tokenNotSet: "No token configured",
  singleNeedsToken: "Single-token mode needs a token: set the `token` option to a token address or \"ETH\".",
  notFlippable: "{symbol} can't be flipped",
  // flip progress
  stepPreviewing: "Checking the odds…",
  stepApproving: "Approve {symbol} in your wallet",
  stepApproveSent: "Approving {symbol}…",
  stepSigning: "Confirm the flip in your wallet",
  stepFlipSent: "Flipping…",
  stepWrapping: "Confirm wrapping ETH in your wallet",
  stepWrapSent: "Wrapping ETH…",
  stepBatch: "Confirm in your wallet",
  drawing: "Drawing…",
  stillDrawing: "Still drawing…",
  waitingRandomness: "Waiting for randomness",
  slowRandomness: "Randomness is slow right now. Your flip is safe: it settles as soon as it arrives.",
  landing: "Landing…",
  // result
  heads: "Heads.",
  tails: "Tails.",
  won: "You won.",
  lost: "Not this time.",
  refunded: "Refunded.",
  resultWon: "{amount} {symbol} was sent to your wallet.",
  resultWonClaim: "{amount} {symbol} is ready to claim on flipper.family (this flip settled in safe mode).",
  resultWinPending: "Your {stake} stake is back. Your winnings are being settled and will arrive shortly.",
  resultWonFallback: "Your {stake} stake is back, and your winnings were paid as {bonus}.",
  resultLost: "Your {stake} stake went to the house.",
  resultRefunded: "The randomness never arrived, so the flip was cancelled and your {stake} stake was returned.",
  settling: "settling winnings…",
  wethPayout: "Winnings arrive as WETH.",
  // pending wins (WinPending: the stake is back, the winnings are owed; anyone can retry the payout)
  // drawdown circuit breaker: the protocol is locked; flips whose randomness arrived meanwhile settle after it
  locked: "Flips are paused",
  lockedNote: "Flips are paused while the treasury is protected. In-flight flips settle after it reopens.",
  deferredTitle: "Settling after pause",
  deferredBody: "The coin landed while flips were paused. Your stake is safe: this flip settles once the treasury reopens.",
  deferredCta: "Waiting for the treasury to reopen",
  settleNow: "Settle now",
  settlingNow: "Settling…",
  settleReady: "Settle this flip now (anyone can)",
  settleWaiting: "It can be settled once the treasury reopens.",
  payoutSettling: "Payout being settled",
  payoutOwed: "{amount} {symbol} owed",
  retryPayout: "Retry payout",
  payingOut: "Paying out…",
  payoutReady: "Pay out the winnings now (anyone can)",
  payoutChecking: "Checking whether the payout can go through…",
  payoutNotYet: "Can't be bought right now.",
  payoutAuto: "Automatic payout by {time} (in {duration})",
  payoutDue: "Automatic payout is due now",
  payoutAlreadyPaid: "Already paid out.",
  payoutPaid: "Paid out: {amount} {symbol}",
  pendingWinsOne: "A win is being paid out",
  pendingWinsMany: "{count} wins are being paid out",
  // form
  amountLabel: "Amount of {symbol} to flip",
  balance: "Balance",
  max: "MAX",
  winChance: "Win chance",
  pays: "Pays",
  fee: "Fee",
  oddsBelow: "Odds {points} pts below usual",
  oddsBelowShort: "Odds −{points} pts",
  oddsBelowHelp:
    "This token's swap fees are high, so the house trims the win chance instead of the payout: {points} percentage points below the usual odds. Smaller stakes are trimmed less.",
  // picker
  chooseToken: "Choose a token",
  searchTokens: "Search name, ticker or address",
  sectionListed: "Flippable",
  sectionEligible: "Listable",
  sectionUnsupported: "Not supported",
  /** @deprecated unused since the picker's checkmarks (checkListed / checkLaunchpad) */
  verifiedBy: "Verified by {sources}",
  checkListed: "Whitelisted by flipper",
  checkLaunchpad: "Verified launch",
  nativeEth: "Native ETH, flipped as WETH",
  houseToken: "House token · {multiple} payout",
  noResults: "No tokens match “{query}”",
  loadingTokens: "Loading tokens…",
  tokensError: "Couldn't load the token list.",
  retry: "Retry",
  close: "Close",
  // listing
  listTitle: "{symbol} isn't listed yet",
  listBody: "Anyone can list it: one transaction, and it's flippable for everyone.",
  listButton: "List {symbol}",
  listChecking: "Checking its liquidity…",
  listConfirm: "Confirm the listing in your wallet",
  listSending: "Listing {symbol}…",
  listDone: "{symbol} is listed. Flip away.",
  listBlocked: "{symbol} can't be listed: {reason}",
  unsupported: "{symbol} can't be flipped: {reason}",
  listingOff: "{symbol} isn't listed on flipper yet.",
  // WETH
  unwrapNote: "You have {amount} WETH.",
  unwrap: "Unwrap to ETH",
  unwrapping: "Unwrapping…",
  unwrapped: "Unwrapped to ETH.",
  // misc
  poweredBy: "Powered by",
  viewTx: "View transaction",
  addToWallet: "Add {symbol} to wallet",
  openWidget: "Flip",
  coinIdle: "Coin",
  coinSpinning: "Coin flipping, waiting for randomness",
  coinHeads: "Coin landed heads: you won",
  coinTails: "Coin landed tails: you lost",
  dialogLabel: "Coin flip",
};

export type FlipperStrings = typeof en;

export const es: FlipperStrings = {
  brand: "flipper",
  connect: "Conectar billetera",
  connectShort: "Conectar",
  connecting: "Conectando…",
  switchChain: "Cambiar a {chain}",
  switching: "Cambiando…",
  wrongNetwork: "Red incorrecta",
  tagline: "Doble o nada",
  taglineSub: "Cara paga {multiple} en {symbol}. Justo y verificable.",
  loading: "Cargando…",
  notLive: "Aún no disponible en esta red",
  unreachable: "No se puede conectar con {chain}",
  paused: "Las apuestas están en pausa",
  enterAmount: "Introduce una cantidad",
  belowMin: "El mínimo es {amount} {symbol}",
  aboveMax: "El máximo es {amount} {symbol}",
  insufficient: "No tienes suficiente {symbol}",
  needFee: "Necesitas {native} para la tarifa de aleatoriedad",
  pricing: "Calculando…",
  cantPrice: "No se pudo cotizar esta apuesta",
  flip: "Lanzar {amount} {symbol}",
  flipAgain: "Lanzar otra vez",
  selectToken: "Elige un token",
  tokenNotSet: "Falta configurar el token",
  singleNeedsToken: "El modo de un solo token necesita un token: define la opción `token` con una dirección o \"ETH\".",
  notFlippable: "{symbol} no se puede lanzar",
  stepPreviewing: "Comprobando las probabilidades…",
  stepApproving: "Aprueba {symbol} en tu billetera",
  stepApproveSent: "Aprobando {symbol}…",
  stepSigning: "Confirma el lanzamiento en tu billetera",
  stepFlipSent: "Lanzando…",
  stepWrapping: "Confirma el wrap de ETH en tu billetera",
  stepWrapSent: "Convirtiendo ETH…",
  stepBatch: "Confirma en tu billetera",
  drawing: "Sorteando…",
  stillDrawing: "Todavía sorteando…",
  waitingRandomness: "Esperando la aleatoriedad",
  slowRandomness: "La aleatoriedad va lenta. Tu apuesta está a salvo: se liquida en cuanto llegue.",
  landing: "Cayendo…",
  heads: "Cara.",
  tails: "Cruz.",
  won: "¡Ganaste!",
  lost: "Esta vez no.",
  refunded: "Reembolsado.",
  resultWon: "Se enviaron {amount} {symbol} a tu billetera.",
  resultWonClaim: "{amount} {symbol} están listos para reclamar en flipper.family (liquidada en modo seguro).",
  resultWinPending: "Recuperaste tu apuesta de {stake}. Tus ganancias se están liquidando y llegarán en breve.",
  resultWonFallback: "Recuperaste tu apuesta de {stake} y tus ganancias se pagaron como {bonus}.",
  resultLost: "Tu apuesta de {stake} fue para la casa.",
  resultRefunded: "La aleatoriedad no llegó, así que se canceló y se devolvió tu apuesta de {stake}.",
  settling: "liquidando ganancias…",
  wethPayout: "Las ganancias llegan como WETH.",
  locked: "Lanzamientos en pausa",
  lockedNote: "Los lanzamientos están en pausa mientras se protege la tesorería. Los que están en curso se liquidan cuando se reabra.",
  deferredTitle: "Se liquida tras la pausa",
  deferredBody: "La moneda cayó mientras los lanzamientos estaban en pausa. Tu apuesta está a salvo: se liquida cuando se reabra la tesorería.",
  deferredCta: "Esperando a que se reabra la tesorería",
  settleNow: "Liquidar ahora",
  settlingNow: "Liquidando…",
  settleReady: "Liquida este lanzamiento ahora (cualquiera puede hacerlo)",
  settleWaiting: "Podrá liquidarse cuando se reabra la tesorería.",
  payoutSettling: "Liquidando el pago",
  payoutOwed: "se te deben {amount} {symbol}",
  retryPayout: "Reintentar pago",
  payingOut: "Pagando…",
  payoutReady: "Cobra las ganancias ahora (cualquiera puede hacerlo)",
  payoutChecking: "Comprobando si el pago puede hacerse…",
  payoutNotYet: "Ahora no se pueden comprar.",
  payoutAuto: "Pago automático antes del {time} (en {duration})",
  payoutDue: "El pago automático ya puede hacerse",
  payoutAlreadyPaid: "Ya se pagó.",
  payoutPaid: "Pagado: {amount} {symbol}",
  pendingWinsOne: "Se está pagando una ganancia",
  pendingWinsMany: "Se están pagando {count} ganancias",
  amountLabel: "Cantidad de {symbol} a lanzar",
  balance: "Saldo",
  max: "MÁX",
  winChance: "Probabilidad",
  pays: "Paga",
  fee: "Tarifa",
  oddsBelow: "Probabilidad {points} pts por debajo",
  oddsBelowShort: "Prob. −{points} pts",
  oddsBelowHelp:
    "Las comisiones de este token son altas, así que la casa reduce la probabilidad en lugar del pago: {points} puntos por debajo de lo habitual. Las apuestas pequeñas se recortan menos.",
  chooseToken: "Elige un token",
  searchTokens: "Busca nombre, ticker o dirección",
  sectionListed: "Disponibles",
  sectionEligible: "Se pueden listar",
  sectionUnsupported: "No compatibles",
  verifiedBy: "Verificado por {sources}",
  checkListed: "En la lista blanca de flipper",
  checkLaunchpad: "Lanzamiento verificado",
  nativeEth: "ETH nativo, se lanza como WETH",
  houseToken: "Token de la casa · paga {multiple}",
  noResults: "Ningún token coincide con “{query}”",
  loadingTokens: "Cargando tokens…",
  tokensError: "No se pudo cargar la lista de tokens.",
  retry: "Reintentar",
  close: "Cerrar",
  listTitle: "{symbol} aún no está listado",
  listBody: "Cualquiera puede listarlo: una transacción y queda disponible para todos.",
  listButton: "Listar {symbol}",
  listChecking: "Comprobando su liquidez…",
  listConfirm: "Confirma el listado en tu billetera",
  listSending: "Listando {symbol}…",
  listDone: "{symbol} está listado. ¡A lanzar!",
  listBlocked: "{symbol} no se puede listar: {reason}",
  unsupported: "{symbol} no se puede lanzar: {reason}",
  listingOff: "{symbol} aún no está listado en flipper.",
  unwrapNote: "Tienes {amount} WETH.",
  unwrap: "Convertir a ETH",
  unwrapping: "Convirtiendo…",
  unwrapped: "Convertido a ETH.",
  poweredBy: "Con tecnología de",
  viewTx: "Ver transacción",
  addToWallet: "Añadir {symbol} a la billetera",
  openWidget: "Lanzar",
  coinIdle: "Moneda",
  coinSpinning: "Moneda girando, esperando la aleatoriedad",
  coinHeads: "La moneda cayó en cara: ganaste",
  coinTails: "La moneda cayó en cruz: perdiste",
  dialogLabel: "Lanzamiento de moneda",
};

export const LOCALES: Record<string, FlipperStrings> = { en, es };

/** The string table for `locale` ("es-MX" → es), with `overrides` applied. */
export function stringsFor(locale: string | undefined, overrides?: Partial<FlipperStrings> | null): FlipperStrings {
  const tag = String(locale ?? "en").toLowerCase();
  // own keys only: `locale=__proto__` (or "constructor") must fall back to English, not to Object.prototype
  const own = (k: string | undefined) => (k !== undefined && Object.prototype.hasOwnProperty.call(LOCALES, k) ? LOCALES[k] : undefined);
  const base = own(tag) ?? own(tag.split(/[-_]/)[0]) ?? en;
  if (!overrides || typeof overrides !== "object") return base;
  const out = { ...base };
  for (const [k, v] of Object.entries(overrides)) {
    if (typeof v === "string" && Object.prototype.hasOwnProperty.call(en, k)) (out as Record<string, string>)[k] = v;
  }
  return out;
}

/** "Flip {amount} {symbol}" + { amount: "10", symbol: "FLIPPER" } → "Flip 10 FLIPPER" */
export function fmt(template: string, vars: Record<string, string | number | undefined> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => {
    const v = vars[k];
    return v === undefined ? "" : String(v);
  });
}
